apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: test-web-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: test-web-deployment
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50